### PR TITLE
OCaml.4.08 and Cmdliner.1.1.0

### PR DESCRIPTION
**Pull request by MisterDA**
Bump lower dependencies.

### CODE REVIEW

**Comment by dinosaure** [comment]
May be a `dune promote` will fix the CI :+1:. Then, I will happy to merge and release.

**Comment by MisterDA** [comment]
> May be a `dune promote` will fix the CI

`dune runtest && dune promote`

The CI is mostly green: the two failing parts are ocamlformat that could be updated, and a weird linking error on debian-11-4.13_x86_32.

**Comment by MisterDA** [comment]
Note that cmdliner's maintainer asked not to depend on the exit codes of the program for expect tests.
https://discuss.ocaml.org/t/ann-cmdliner-1-1-0/9295/2

**Comment by dinosaure** [comment]
Thanks!

**Pull request merged**
